### ISSUE TITLE
bug fix and development

### ISSUE THREAD

**Issue by lhj010217** [WebProgramming21-2/Quiz-Website#28]
## 작업 설명
1. 회원정보에 score, rank 추가
2. 점수 부여방식 세분화
3. quiz.jsp에서 뒤로가기, 새로고침을 하면 문제를 다시 풀 수 있음.
4. 아이디 생성시 욕설 필터링 기능
5. registerOut.jsp에서 아이디와 비밀번호를 입력하면, 현재 로그인한 아이디가 아닌 다른 아이디도 탈퇴시킬 수 있음. 아이디 입력버튼 삭제

## TODO
- [x] 회원정보에 score와 rank 표시 추가
- [x] 점수 부여방식 변경
- [ ] 퀴즈페이지에서 뒤로가기, 새로고침기능 삭제?
- [ ] 아이디 생성시 욕설 필터링
- [x] registerOut.jsp에서 아이디 입력버튼 삭제. sql은 session에 저장된 userID를 이용.

## 참고사항
2번의 경우 int형으로 저장되던 점수를 float으로 바꾸어줌.
따라서 db4free에서 score행 속성에서 종류를 int에서 float으로 바꾸어주어야함.
