### ISSUE TITLE
bug fix

### ISSUE THREAD

**Issue by lhj010217** [WebProgramming21-2/Quiz-Website#30]
## 작업 설명
> 1. mypage.jsp에서 score와 rank를 볼 수 있도록함.
> 2. registerOut,jsp에서 id 입력 버튼 삭제
> 3. quiz에서 score를 session에 저장

## TODO
- [x] mypage.jsp에서 score와 rank를 볼 수 있도록 구현
- [x] registerOut,jsp에서 id 입력 버튼 삭제, registerOutAction에서 id는 session에서 받아옴.
- [x] quiz.jsp, quizStart.jsp에서 score는 javascript의 sessionStorage를 사용. 

## 참고사항
문제를 다 풀면 beforeRank.jsp에 score를 get방식으로 넘겨주지만 jsp가 가장 먼저 동작하여 db에 score를 저장하기 때문에 url로 점수를 조작할 수는 없음.
