### ISSUE TITLE
Quizmode design or Ranking design

### ISSUE THREAD

**Issue by seungb1027** [WebProgramming21-2/Quiz-Website#9]
## 작업 설명
이번주에는 퀴즈모드 화면 디자인 혹은 랭킹 보여주는 화면 디자인 및 버그 수정할 예정

## TODO
- [x] 퀴즈모드 화면 디자인
- [x] 랭킹모드 화면 디자인
- [x] 1week bug figs

## 참고사항
필요 시 작성
